### ISSUE TITLE
mpi virtual form 11/7/18 feedback

### ISSUE THREAD

**Issue by hppritcha** [mpiwg-sessions/sessions-issues#2]
Feedback from 11/7/18 virtual form that needs to be addressed by 11/19/18

- [x] need to incorporate ```MPI_Comm_create_from_group``` from ticket mpi-forum/mpi-standard#44 into mpi-forum/mpi-standard#55
- [x] need to incorporate ```MPI_File_open_from_group``` from ticket mpi-forum/mpi-standard#44 into mpi-forum/mpi-standard#55
- [x] need to incorporate ```MPI_Win_create_from_group``` from ticket mpi-forum/mpi-standard#46 into mpi-forum/mpi-standard#55
- [x] add a simplified example for initializing using ```mpi://world``` (Rolf wants to see concurrency in at least one example, multiple library, etc.)
- [x] modify the current more complex example to use a user-specified pset name (Rolf wants to see concurrency in at least one example.  Concurrency here could be both with multiple threads in each process creating sessions/comms, as well as the multiple libraries example)
- [x] add wording about sessions isolation concept and limitations of mixing objects derived from different sessions in, for example ```MPI_Waitall``` etc.
- [x] lines 36-37 on page 425 Seesion vs Session
- [x] line 20 on page 390 - is turned should be returned
- [x] rework the NULL terminated language for ```MPI_Session_get_nth_pset```.  This doesn't comport with Fortran.  Use wording like that used for ```MPI_info_get```

**Comment by hppritcha** [comment]
closing this issue since we've ticked off all the items.
